---
abstract: 'get Chord Tone List from Chord Name'
author:
  - 'Dai Okabayashi <bayashi@cpan.org>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Music-Chord-Note
provides:
  Music::Chord::Note:
    file: lib/Music/Chord/Note.pm
    version: 0.07
requires:
  Carp: 0
  Test::More: 0
  perl: v5.6.2
resources:
  license: http://dev.perl.org/licenses/
version: 0.07
